# Generated by Django 4.2.4 on 2023-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDtkt', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
