# Generated by Django 4.2.4 on 2023-08-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_info',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket_info',
            name='name',
        ),
    ]
